name: Test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install
      run: |
        sudo apt-get -yq install redis-server
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Test
      run: bundle exec rake test
